version: "3.8"
services:
  bot:
    build: .
    secrets:
      - my_bot_env
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
secrets:
  my_bot_env:
    external: true
